version: "3"
services:
   
    dt-be:
        image: dt-be:1.2.3
        container_name: dt-be
        command: npm start
        ports:
          - "8080:8080"
      
    dt-fe:
        image: dt-fe:1.2.4
        container_name: dt-fe
        command: npm start
        depends_on:
          - dt-be
          - dt-nh
        ports:
          - "3000:3000"
        expose:
            - "3000"

    dt-nh:
        image: dt-nh:1.0.23
        container_name: dt-nh
        command: npm start
        ports:
          - "8081:8081"
          - "8082:8082"
          - "8083:8083"
        expose:
            - "8081"
            - "8082"
            - "8083"

    mongo:
        image: mongo:4.4
        command: --nojournal
        container_name: mongo

    orion:
        image: fiware/orion-ld:latest
        links:
            - mongo
        ports:
            - "1026:1026"
        command: -dbhost mongo
        container_name: orion
        expose:
            - "1026"
        depends_on:
            - mongo
